### ISSUE TITLE
Add Support for Domain Enabled Flag

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-aws-kops-state-backend#6]
## what
* Add flag to disable dns zone creation

## why
* Kops clusters created in gossip mode do not require dns zones

## references
* https://github.com/cloudposse/terraform-aws-route53-cluster-zone/issues/9

**Comment by aknysh** [comment]
Addressed in https://github.com/cloudposse/terraform-aws-kops-state-backend/pull/7
